BEGIN;

CREATE TABLE clientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE,
    cidade VARCHAR(100) NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL UNIQUE,
    descricao TEXT
);

CREATE TABLE produtos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id INTEGER NOT NULL REFERENCES categorias(id),
    nome VARCHAR(120) NOT NULL,
    preco NUMERIC(10, 2) NOT NULL CHECK (preco >= 0),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE pedidos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INTEGER NOT NULL REFERENCES clientes(id),
    data_pedido TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL,
    valor_total NUMERIC(12, 2) NOT NULL CHECK (valor_total >= 0)
);

CREATE TABLE itens_pedido (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INTEGER NOT NULL REFERENCES pedidos(id),
    produto_id INTEGER NOT NULL REFERENCES produtos(id),
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    preco_unitario NUMERIC(10, 2) NOT NULL CHECK (preco_unitario >= 0),
    UNIQUE (pedido_id, produto_id)
);

INSERT INTO clientes (id, nome, email, cidade, criado_em) VALUES
    (1, 'Ana Lima', 'ana.lima@example.com', 'Sao Paulo', '2026-01-05 09:00:00-03'),
    (2, 'Bruno Souza', 'bruno.souza@example.com', 'Curitiba', '2026-01-08 10:30:00-03'),
    (3, 'Carla Mendes', 'carla.mendes@example.com', 'Recife', '2026-01-12 14:10:00-03'),
    (4, 'Diego Alves', 'diego.alves@example.com', 'Belo Horizonte', '2026-01-20 16:45:00-03');

INSERT INTO categorias (id, nome, descricao) VALUES
    (1, 'Informatica', 'Computadores e acessorios'),
    (2, 'Escritorio', 'Itens para o ambiente de trabalho'),
    (3, 'Audio', 'Fones e caixas de som'),
    (4, 'Livros', 'Livros tecnicos e de negocios');

INSERT INTO produtos (id, categoria_id, nome, preco, ativo) VALUES
    (1, 1, 'Notebook Pro 14', 5299.90, TRUE),
    (2, 1, 'Mouse sem fio', 129.90, TRUE),
    (3, 2, 'Cadeira ergonomica', 1199.00, TRUE),
    (4, 2, 'Caderno executivo', 39.90, TRUE),
    (5, 3, 'Fone bluetooth', 349.50, TRUE),
    (6, 4, 'SQL para Analytics', 89.90, TRUE);

INSERT INTO pedidos (id, cliente_id, data_pedido, status, valor_total) VALUES
    (1, 1, '2026-02-01 10:15:00-03', 'pago', 5429.80),
    (2, 2, '2026-02-03 15:20:00-03', 'enviado', 1238.90),
    (3, 1, '2026-02-08 11:05:00-03', 'entregue', 439.40),
    (4, 3, '2026-02-11 09:40:00-03', 'pago', 299.70),
    (5, 4, '2026-02-15 17:30:00-03', 'cancelado', 129.90);

INSERT INTO itens_pedido (id, pedido_id, produto_id, quantidade, preco_unitario) VALUES
    (1, 1, 1, 1, 5299.90),
    (2, 1, 2, 1, 129.90),
    (3, 2, 3, 1, 1199.00),
    (4, 2, 4, 1, 39.90),
    (5, 3, 5, 1, 349.50),
    (6, 3, 6, 1, 89.90),
    (7, 4, 2, 2, 129.90),
    (8, 5, 2, 1, 129.90),
    (9, 4, 4, 1, 39.90);

SELECT setval(pg_get_serial_sequence('clientes', 'id'), (SELECT MAX(id) FROM clientes));
SELECT setval(pg_get_serial_sequence('categorias', 'id'), (SELECT MAX(id) FROM categorias));
SELECT setval(pg_get_serial_sequence('produtos', 'id'), (SELECT MAX(id) FROM produtos));
SELECT setval(pg_get_serial_sequence('pedidos', 'id'), (SELECT MAX(id) FROM pedidos));
SELECT setval(pg_get_serial_sequence('itens_pedido', 'id'), (SELECT MAX(id) FROM itens_pedido));

COMMIT;
